---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meta-dados-rio-web
  namespace: beta-meta-dados-rio
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  selector:
    matchLabels:
      app: meta-dados-rio-web
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: meta-dados-rio-web
    spec:
      containers:
        - name: meta-dados-rio-web
          image: gcr.io/PROJECT_ID/IMAGE_NAME:TAG
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: meta-dados-rio-web-secrets
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
      restartPolicy: Always

---
# Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: meta-dados-rio-web
  name: meta-dados-rio-web
  namespace: beta-meta-dados-rio
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 3000
  selector:
    app: meta-dados-rio-web

---
# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: meta-dados-rio-web-ingress
  namespace: beta-meta-dados-rio
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - beta.meta.dados.rio
      secretName: meta-dados-rio-web-tls
  rules:
    - host: beta.meta.dados.rio
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: meta-dados-rio-web
                port:
                  number: 80
